POST /dc HTTP/1.1 
Host: localhost:5000
Content-Type: application/json

{
    "datacenter" : "test1",
    "kw":[0,0,0,0,0,0,0,0,0,0,0,0.5],
    "racks":2
}

###
POST /dc HTTP/1.1 
Host: localhost:5000
Content-Type: application/json

{
    "datacenter" : "test",
    "kw":[0,0,0,0,100,0,0,0,0,0,0,0.5],
    "racks":2
}

###
PUT /dc/task HTTP/1.1 
Host: localhost:5000
Content-Type: application/json

{
    "datacenter" : "test",
    "usage" : 22
}
###
GET /status HTTP/1.1 
Host: localhost:5000